"""Write docker-compose .env.local from the deployed app secret.

The Terraform state can live anywhere: the module root, an example directory, or
a scratch workspace with a live run. Point the script at it with
``--terraform-dir``; it defaults to the current directory so a direct call from
the workspace works without flags. The justfile target passes the directory just
was invoked from, so ``just -f <chatbot/justfile> dump-local-env`` works from a
workspace outside the repository.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path
from subprocess import CompletedProcess

DEFAULT_TERRAFORM_DIR = Path.cwd()
DEFAULT_OUTPUT = Path(__file__).resolve().parent.parent / "secrets" / ".env.local"

_CHAINLIT_KEYS = frozenset(
    {"CHAINLIT_AUTH_SECRET", "CHAINLIT_DEMO_PASSWORD", "CHAINLIT_DEMO_USERNAME"}
)
_CONTAINER_ENV_KEYS = (
    "MONGODB_DATABASE",
    "AUTOEMBED_MODEL",
    "LLM_PROVIDER",
    "BEDROCK_MODEL",
    "AWS_REGION",
    "ENABLE_LLM",
    "TOP_K",
    "CHUNK_MAX_TOKENS",
)
_ENV_ORDER = (
    "MONGODB_URI",
    "MONGODB_DATABASE",
    "AUTOEMBED_MODEL",
    "LLM_PROVIDER",
    "BEDROCK_MODEL",
    "AWS_REGION",
    "AWS_PROFILE",
    "ENABLE_LLM",
    "TOP_K",
    "CHUNK_MAX_TOKENS",
)

Run = Callable[..., CompletedProcess[str]]


class DumpLocalEnvError(RuntimeError):
    def __init__(self, message: str, *, exit_code: int = 1) -> None:
        super().__init__(message)
        self.exit_code = exit_code


def resolve_aws_profile(override: str | None = None) -> str | None:
    """The AWS profile the container should use, taken from the caller's environment."""
    if override:
        return override
    return os.environ.get("AWS_PROFILE") or os.environ.get("AWS_DEFAULT_PROFILE") or None


def local_env_from_secret(
    secret: dict[str, object],
    *,
    mongodb_uri: str | None,
) -> tuple[dict[str, str], list[str]]:
    warnings: list[str] = []
    env: dict[str, str] = {}
    container = secret.get("container")
    if not isinstance(container, dict):
        container = {}
    container_env = container.get("env")
    if not isinstance(container_env, dict):
        container_env = {}
    secret_keys = container.get("secret_keys")
    if not isinstance(secret_keys, list):
        secret_keys = []

    if mongodb_uri:
        env["MONGODB_URI"] = mongodb_uri
    else:
        warnings.append(
            "MONGODB_URI omitted: set features.debug_access_for_cluster = true, "
            "re-apply the module, then re-run just dump-local-env."
        )

    for key in _CONTAINER_ENV_KEYS:
        if key in container_env:
            env[key] = str(container_env[key])

    for key in secret_keys:
        if not isinstance(key, str) or key in _CHAINLIT_KEYS or key in env:
            continue
        value = secret.get(key)
        if value is not None:
            env[key] = str(value)

    return env, warnings


def render_env_file(env: dict[str, str], *, secret_name: str) -> str:
    ordered = [key for key in _ENV_ORDER if key in env]
    ordered.extend(sorted(key for key in env if key not in _ENV_ORDER))
    lines = [
        "# Generated by: just dump-local-env",
        f"# Source secret: {secret_name}",
        "",
    ]
    lines.extend(f"{key}={_quote_env_value(env[key])}" for key in ordered)
    return "\n".join(lines) + "\n"


def dump_local_env(
    *,
    terraform_dir: Path,
    output: Path,
    region: str | None = None,
    secret_name: str | None = None,
    mongodb_uri: str | None = None,
    aws_profile: str | None = None,
    run: Run = subprocess.run,
) -> Path:
    resolved_secret_name = secret_name or _chatbot_secret_name(terraform_dir, run=run)
    if not resolved_secret_name:
        raise DumpLocalEnvError(
            f"no chatbot output in {terraform_dir}; apply the module there, "
            "or pass --terraform-dir pointing at the workspace with the state."
        )

    resolved_region = region
    secret = _fetch_secret_json(resolved_secret_name, resolved_region or "us-east-1", run=run)
    if not resolved_region:
        aws_region = secret.get("aws_region")
        resolved_region = str(aws_region) if aws_region else "us-east-1"

    public_uri = mongodb_uri or _terraform_raw(terraform_dir, "connection_string_public", run=run)
    env, warnings = local_env_from_secret(secret, mongodb_uri=public_uri)
    # Bedrock signs with AWS credentials. Record the caller's profile so the
    # container uses the same ones as the CLI, instead of the compose default.
    if profile := resolve_aws_profile(aws_profile):
        env["AWS_PROFILE"] = profile
    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)

    content = render_env_file(env, secret_name=resolved_secret_name)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content)
    return output


def _quote_env_value(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def _chatbot_secret_name(terraform_dir: Path, *, run: Run) -> str | None:
    """Read the chatbot secret name from the module's `chatbot` object output."""
    try:
        completed = run(
            ["terraform", f"-chdir={terraform_dir}", "output", "-json", "chatbot"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    try:
        value = json.loads(completed.stdout)
    except json.JSONDecodeError:
        return None
    if not isinstance(value, dict):
        return None
    secret_name = value.get("secret_name")
    return secret_name if isinstance(secret_name, str) and secret_name else None


def _terraform_raw(terraform_dir: Path, name: str, *, run: Run) -> str | None:
    try:
        completed = run(
            ["terraform", f"-chdir={terraform_dir}", "output", "-raw", name],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    value = completed.stdout.strip()
    if not value or value == "null":
        return None
    return value


def _fetch_secret_json(secret_name: str, region: str, *, run: Run) -> dict[str, object]:
    try:
        completed = run(
            [
                "aws",
                "secretsmanager",
                "get-secret-value",
                "--secret-id",
                secret_name,
                "--region",
                region,
                "--query",
                "SecretString",
                "--output",
                "text",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise DumpLocalEnvError(f"could not read secret {secret_name!r} in {region}") from exc
    return json.loads(completed.stdout)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Dump local Docker env from the app secret.")
    parser.add_argument(
        "--terraform-dir",
        type=Path,
        default=DEFAULT_TERRAFORM_DIR,
        help="Terraform workspace holding the module state (default: the current directory).",
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--region")
    parser.add_argument("--secret-name")
    parser.add_argument("--mongodb-uri")
    parser.add_argument(
        "--aws-profile",
        help="AWS profile for the container (default: AWS_PROFILE or AWS_DEFAULT_PROFILE).",
    )
    args = parser.parse_args(argv)
    try:
        path = dump_local_env(
            terraform_dir=args.terraform_dir,
            output=args.output,
            region=args.region,
            secret_name=args.secret_name,
            mongodb_uri=args.mongodb_uri,
            aws_profile=args.aws_profile,
        )
    except DumpLocalEnvError as exc:
        print(exc, file=sys.stderr)
        return exc.exit_code
    print(path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
